<?php

namespace AthenaBridge\Laminas\Session;

class Container extends \Laminas\Session\Container
{
    protected static $managerDefaultClass = SessionManager::class;

    public static function getDefaultManager():object
    {
        return parent ::getDefaultManager(); // TODO: Change the autogenerated stub
    }
}